import { EditModal } from './Modal'
import { AlingMenu, ListMenu, TabsMenu, TypeMenu, getTabs, isBlockProps, setTabs } from './BlockProps'
import {
  BlockElement,
  defaultBlock,
  getText,
  setText,
  Child,
  t,
  t1,
  t2,
  t3,
  BockType,
  Align,
  List,
  Tabs,
  characters,
  defaulHtml,
  defaultChild,
  getHTML,
  getTextFormat,
} from './Data'
import { Element } from './Element'
import { Leaf } from './Mark'
import {
  ColorButton,
  BackButton,
  FontSize,
  FontsFamily,
  toggleMark,
  FontStyle,
  MarkMenu,
  MarkButton,
} from './MarkProps'
import { hotKeysValue } from './HotKeys'
import { VerElement, VerLeaf } from './Ver'
import { Props, Texto, TextToHTML } from './Main'
export type { BlockElement, Props as slateProps }
export {
  getTabs,
  isBlockProps,
  setTabs,
  MarkButton,
  BockType,
  Align,
  List,
  Tabs,
  characters,
  defaulHtml,
  defaultChild,
  getHTML,
  getTextFormat,
  Child,
  t,
  t1,
  t2,
  t3,
  VerElement,
  VerLeaf,
  defaultBlock,
  hotKeysValue,
  Texto,
  TextToHTML,
  getText,
  setText,
  Element,
  Leaf,
  AlingMenu,
  ListMenu,
  TabsMenu,
  TypeMenu,
  ColorButton,
  FontStyle,
  MarkMenu,
  BackButton,
  FontSize,
  FontsFamily,
  toggleMark,
  EditModal,
}
